# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install ply
    - pip install coveralls
    - pip install timeseries
    - pip install pype
    - pip install tsdb
    - pip install procs
script:
    - py.test --doctest-modules
after_success:
    - coveralls