# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

virtualenv:
  system_site_packages: true
language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install ply
    - sudo apt-get install -qq python-scipy
    - pip install coveralls
script:
    - py.test --doctest-modules
after_success:
    - coveralls
