# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

language: python
python:
  - 3.5

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pandas statsmodels tornado
  - conda install --yes pytest pytest-cov
  - conda install --yes ply
  - conda install --yes -c omnia python-coveralls=2.5.0

# Run test
script:
  - py.test --doctest-modules

# Calculate coverage
after_success:
  - coveralls 
  
############################### ORIGINAL #############################################
#language: python
#python:
#    - "3.5"
#before_install:
#    - pip install pytest pytest-cov
#    - pip install ply
#    - pip install coveralls
#script:
#    - py.test --doctest-modules
#after_success:
#    - coveralls
