# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/

language: python

matrix:
  include:
    - python: 3.5
      env: NUMPY=1.10 SCIPY=0.16


before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda
 - pip install pytest pytest-cov
 - pip install ply
 - pip install coveralls

install:
 - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
 - source activate test
 - conda install --yes numpy=$NUMPY scipy=$SCIPY matplotlib pip
 - pip install setuptools
# - [ ... some other packages to install ... ]
 - python setup.py install

script:
 - py.test --doctest-modules

after_success:
 - coveralls
#language: python
#sudo: required

#python:
#    - "3.5"
#before_install:
#    - pip install pytest pytest-cov
#    - pip install ply
#    - sudo apt-get install python-scipy
#    - pip install coveralls
#script:
#    - alias scipy='python-scipy'
#    - py.test --doctest-modules
#after_success:
#    - coveralls
#matrix:
 # include:
  #  - python: "3.5"
   #   env: DEPS="numpy scipy matplotlib pillow pandas!=0.18.0 scikit-image pyyaml pytables numba"
#python:
#    - "3.5"
#install:
  # See:
  # https://groups.google.com/a/continuum.io/forum/#!topic/conda/RSFENqovnro
 # - conda update --yes --no-deps conda
  # OK, this used to *fix* the build, but now it *breaks* the build.
  # If you're reading this, good luck out there. I'm not sure what to tell you.
  # - conda update --yes conda
  #- conda config --add channels soft-matter
  #- conda create -n testenv --yes $DEPS pip nose setuptools python=$TRAVIS_PYTHON_VERSION
  #- source activate testenv
  
#before_install:
#  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
#  - chmod +x miniconda.sh
#  - ./miniconda.sh -b -p /home/travis/mc
#  - export PATH=/home/travis/mc/bin:$PATH
#  - pip install pytest pytest-cov
#  - pip install ply
#  - pip install coveralls
#script:
#    - py.test --doctest-modules
#after_success:
#    - coveralls
